### ISSUE TITLE
O que é o virtual object em fonologico

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/SignBank-Brasil#11]

**Comment by gstvob** [comment]
Dei uma olhada no código e aparentemente esse campo é pra existir mesmo
olhei no manual lá do signbank e ele descreveu esse campo:
![image](https://user-images.githubusercontent.com/18465203/58725725-42d43200-83b6-11e9-9572-6516d9225e8a.png)

**Comment by ramonrdm** [comment]
O que não tem solução, solucionado está.
