### ISSUE TITLE
enviar arquivos para revisar tradução

### ISSUE THREAD

**Issue by ramonrdm** [ramonrdm/SignBank-Brasil#2]

**Comment by gstvob** [comment]
eu mandei lá pra ronice.

**Comment by ramonrdm** [comment]
favor colocar o arquivo aqui

**Comment by ramonrdm** [comment]
confere eles novamente e envia para o email da reunião, também coloca em destaque as fields da categoria fonológico;

Você se comprometeu a traduzir as coisas básicas;
